### ISSUE TITLE
Hi! I have a question, can GE ASL data be analyzed using the Oxford_ASL? Why the units of perfusion_calib.nii.gz is 6000 but not 60?

### ISSUE THREAD

**Issue by chengzhou95** [ibme-qubic/asl-docs#2]
Hi! I have a question, can GE ASL data be analyzed using the Oxford_ASL? Why the units of perfusion_calib.nii.gz is 6000 but not 60?
[perfusion.nii.gz](https://github.com/ibme-qubic/asl-docs/files/3457266/perfusion.nii.gz)
[perfusion_calib.nii.gz](https://github.com/ibme-qubic/asl-docs/files/3457267/perfusion_calib.nii.gz)

**Comment by mcraig-ibme** [comment]
Apologies for the slow response - I have not been getting GitHub notifications!

The conversion factor is 6000 to convert to the conventional units of ml/100g/min. The factor of 60 accounts for s -> min conversion while the factor of 100 is the conversion from g -> 100g.

**Comment by mcraig-ibme** [comment]
Let me know if there are any further queries - if not I will close this issue.

**Comment by chengzhou95** [comment]
Thank  you  very much. I get it.-------- 原始邮件 --------发件人： Martin Craig <notifications@github.com>日期： 2020年4月17日周五 傍晚5:07收件人： ibme-qubic/asl-docs <asl-docs@noreply.github.com>抄送： chengzhou95 <chengzhou95@zju.edu.cn>, Author <author@noreply.github.com>主    题： Re: [ibme-qubic/asl-docs] Hi! I have a question, can GE ASL data be analyzed using the Oxford_ASL? Why the units of perfusion_calib.nii.gz is 6000 but not 60? (#2)
Let me know if there are any further queries - if not I will close this issue.

**Comment by mcraig-ibme** [comment]
Great, thanks
